apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: e-commerce
configMapGenerator:
  - name: tools-configmap
    literals: 
    - PG_URI=
    - DATABASE=e-commerce
generatorOptions:
  disableNameSuffixHash: true # use a static name
bases:
- ../../../base/tools